### PR TITLE
Create proposal-address-mapping.md

### PR DESCRIPTION
**Pull request by adrianhopebailie**
Proposal for mapping existing accounts to ILP addresses

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
@justmoon , @emschwartz any thoughts on this?

**Comment by emschwartz** [comment]
If you want this in the repo I think it should go in as a numbered RFC

**Comment by adrianhopebailie** [comment]
@emschwartz - it's just a proposal for now, prob could have submitted as an issue first.

It was a lot more verbose in v1 (more explanations etc) but I lost v1 before saving (the perils of editing in the browser) so this was a quick lean v2 to get the idea out there

**Comment by emschwartz** [comment]
Yeah if it's more of a proposal I'd say put it as an issue instead of in the repo. Seems like a fine start to me

**Pull request closed without merging**
