### PR TITLE
crypto-conditions: Add SECP256K1-SHA-256 fulfillment

### PR DESCRIPTION
**Pull request by stevenroose**
Add a new fulfillment that implements an ECDSA signature verification over Bitcoin's secp256k1 curve.

The output is not provided since I didn't get the Grunt task to work.

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
I will merge #131 as soon as I have validated that the ASN.1 changes don't break the new test harness at https://github.com/rfcs/crypto-conditions/

**Comment by adrianhopebailie** [comment]
#131 is merged. Can you rebase and force push a new commit?

**Comment by stevenroose** [comment]
@adrianhopebailie I just rebased.

The only thing missing is a cost value. I didn't fully follow the new cost calculation decisions. I don't thing ECDSA is operationally similar to either Ed25519 or RSA, so I don't know how to specify a sensible heuristic.

**Comment by adrianhopebailie** [comment]
The cost functions are a very rough estimate of "the number of bytes that would need to be processed by the SHA-256 hash digest algorithm to produce the equivalent amount of work".

I'd recommend running some tests on a machine with a consistent resource configuration and comparing the results of performing a SHA-256 hash and computing RSA, ed25519 and ECDSA signatures on some fixed size messages.

This should give enough data to calculate a cost function that produces a relative cost value in line with the others we have already specified.

@justmoon may also have some suggestions in this regard as we did the initial tests on his machine and I think he still has some of the raw data.

**Comment by stevenroose** [comment]
@justmoon, is it possible for you to come up with a value using your reference machine?

I think it's important to keep in mind that there are some very performant secp256k1 implementations out there that act only on that specific curve like libsecp126k1 or Go's btcec.

**Comment by justmoon** [comment]
> @justmoon, is it possible for you to come up with a value using your reference machine?

Ok, I just ran a rough benchmark and I got 78.721us per signature verification for secp256k1.

Using the same reference number for SHA-256 (2200 bytes/us) that would give us: 78.7 * 2200 = 173140. The nearest power of two is the same as Ed25519, 131072.

That makes sense because Ed25519 and libsecp256k1 [should be a similar speed](http://justmoon.github.io/curvebench/benchmark.html).

**Comment by stevenroose** [comment]
@justmoon so I can use the same heuristic as the Ed25519 one?

**Comment by stevenroose** [comment]
The cost description of Ed25519 says 

> The public key and signature are a fixed size therefore the cost for an ED25519 crypto-condition is fixed at 131072.
> 
>     cost = 131072

However ECDSA signatures are not necessarily fixed-size. The sizes vary slightly.

**Comment by stevenroose** [comment]
I pushed an update, adding a cost of 131072.

**Comment by adrianhopebailie** [comment]
I want to tag the current draft before we push major changes like this so just waiting for some responses to #148

**Comment by stevenroose** [comment]
Ok, sure. Makes sense.

**Comment by adrianhopebailie** [comment]
@stevenroose can you close this PR and replicate it against: https://github.com/rfcs/crypto-conditions/

**Comment by michielbdejong** [comment]
Can this be closed?

**Comment by stevenroose** [comment]
@michielbdejong I should find some time to migrate it to the RFCs repository.  I might have overestimated the usage of this addition, though. Bitcoin cannot do on-chain signature verification of arbitrary messages. This support might land in the future with segwit script versioning, either for classic ECDSA or Schnorr (both over the secp256k1 curve). Until then, it might be useful for Ethereum (Ethereum can do arbitrary message signature verification using `ecrecover()`).

**Comment by emschwartz** [comment]
Closing this PR now as it should move to the rfcs repo

**Pull request closed without merging**
